# TCL File Generated by Component Editor 20.1
# Mon Feb 01 17:13:37 GMT+08:00 2021
# DO NOT MODIFY


# 
# LedMatrix "LedMatrix" v1.0
#  2021.02.01.17:13:37
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module LedMatrix
# 
set_module_property DESCRIPTION ""
set_module_property NAME LedMatrix
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP kbd
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME LedMatrix
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LedMatrix
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LedMatrix.sv SYSTEM_VERILOG PATH ../SpinalHDL/LedMatrix.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point bus
# 
add_interface bus avalon end
set_interface_property bus addressUnits WORDS
set_interface_property bus associatedClock clock
set_interface_property bus associatedReset reset
set_interface_property bus bitsPerSymbol 8
set_interface_property bus burstOnBurstBoundariesOnly false
set_interface_property bus burstcountUnits WORDS
set_interface_property bus explicitAddressSpan 0
set_interface_property bus holdTime 0
set_interface_property bus linewrapBursts false
set_interface_property bus maximumPendingReadTransactions 0
set_interface_property bus maximumPendingWriteTransactions 0
set_interface_property bus readLatency 0
set_interface_property bus readWaitTime 1
set_interface_property bus setupTime 0
set_interface_property bus timingUnits Cycles
set_interface_property bus writeWaitTime 0
set_interface_property bus ENABLED true
set_interface_property bus EXPORT_OF ""
set_interface_property bus PORT_NAME_MAP ""
set_interface_property bus CMSIS_SVD_VARIABLES ""
set_interface_property bus SVD_ADDRESS_GROUP ""

add_interface_port bus bus_write write Input 1
add_interface_port bus bus_address address Input 7
add_interface_port bus bus_writeData writedata Input 32
set_interface_assignment bus embeddedsw.configuration.isFlash 0
set_interface_assignment bus embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment bus embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment bus embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 80000000
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point io
# 
add_interface io conduit end
set_interface_property io associatedClock clock
set_interface_property io associatedReset reset
set_interface_property io ENABLED true
set_interface_property io EXPORT_OF ""
set_interface_property io PORT_NAME_MAP ""
set_interface_property io CMSIS_SVD_VARIABLES ""
set_interface_property io SVD_ADDRESS_GROUP ""

add_interface_port io io_col col Output 35
add_interface_port io io_row row Output 6
